site_name: 心理学のための様相論理入門
site_description: 心理学を学ぶ学生や研究者のための様相論理教科書
site_author: PsycholoStudio
site_url: https://psycholostudio.github.io/Psychology-On-Epistemic-Logic/

repo_name: PsycholoStudio/Psychology-On-Epistemic-Logic
repo_url: https://github.com/PsycholoStudio/Psychology-On-Epistemic-Logic

theme:
  name: material
  language: ja
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: ja
  - git-revision-date-localized:
      type: date
  - privacy:
      links_attr_map:
        target: _blank

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - sane_lists  # リストのパースを改善

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://d3js.org/d3.v4.min.js
  - https://cdn.jsdelivr.net/npm/venn.js@0.2.20/build/venn.min.js
  - javascripts/venn-diagrams.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css

nav:
  - ホーム: index.md
  - 基礎編:
    - 第1章 様相論理入門:
      - 1.1 様相論理の動機と直観: foundations/1-1-modal-motivation.md
      - 1.2 命題論理の復習: foundations/1-2-propositional-logic.md
      - 1.3 述語論理の復習: foundations/1-3-predicate-logic.md
      - 1.4 様相論理の導入: foundations/1-4-modal-introduction.md
      - 1.5 論理と心の関係: foundations/1-5-logic-and-mind.md
    - 第2章 クリプキ意味論:
      - 2.1 可能世界の概念: foundations/2-1-possible-worlds.md
      - 2.2 クリプキフレームとモデル: foundations/2-2-kripke-frames.md
      - 2.3 真理条件と妥当性: foundations/2-3-truth-conditions.md
      - 2.4 フレームの性質: foundations/2-4-frame-properties.md
      - 2.5 一般フレーム理論: foundations/2-5-general-frames.md
    - 第3章 様相論理の体系:
      - 3.1 最小正規様相論理K: foundations/3-1-minimal-logic-k.md
      - 3.2 古典的様相論理: foundations/3-2-classical-systems.md
      - 3.3 証明論: foundations/3-3-proof-theory.md
      - 3.4 対応理論: foundations/3-4-correspondence.md
      - 3.5 証明論的意味論: foundations/3-5-proof-semantics.md
    - 第4章 知識と信念の論理:
      - 4.1 認識論的背景: foundations/4-1-epistemic-background.md
      - 4.2 知識の論理S5: foundations/4-2-knowledge-logic.md
      - 4.3 信念の論理KD45: foundations/4-3-belief-logic.md
      - 4.4 混合システム: foundations/4-4-mixed-systems.md
    - 第5章 認識論理の変種と比較:
      - 5.1 知識の段階理論: foundations/5-1-graded-knowledge.md
      - 5.2 条件付き知識: foundations/5-2-conditional-knowledge.md
      - 5.3 不完全情報の論理: foundations/5-3-incomplete-information.md
      - 5.4 資源制約付き推論: foundations/5-4-resource-bounded.md
      - 5.5 非標準的アプローチ: foundations/5-5-nonstandard.md
  - 応用編:
    - 第1章 心の理論と発達:
      - 1.1 心の理論の発達段階: applications/1-1-theory-of-mind.md
      - 1.2 誤信念課題の形式分析: applications/1-2-false-belief.md