site_name: 心理学のための様相論理入門
site_description: 心理学を学ぶ学生や研究者のための様相論理教科書
site_author: PsycholoStudio
site_url: https://psycholostudio.github.io/Psychology-On-Epistemic-Logic/

repo_name: PsycholoStudio/Psychology-On-Epistemic-Logic
repo_url: https://github.com/PsycholoStudio/Psychology-On-Epistemic-Logic

theme:
  name: material
  language: ja
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: ja
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css

nav:
  - ホーム: index.md
  - 基礎編:
    - 第1章 様相論理入門:
      - 1.1 命題論理の復習: foundations/1-1-propositional-logic.md
      - 1.2 様相論理の動機と直観: foundations/1-2-modal-motivation.md
      - 1.3 様相言語の構文: foundations/1-3-modal-syntax.md
      - 1.4 応用分野概観: foundations/1-4-applications-overview.md
      - 1.5 論理と心の関係: foundations/1-5-logic-and-mind.md
    - 第2章 クリプキ意味論:
      - 2.1 可能世界の概念: foundations/2-1-possible-worlds.md
      - 2.2 クリプキフレームとモデル: foundations/2-2-kripke-frames.md
      - 2.3 真理条件と妥当性: foundations/2-3-truth-conditions.md
  - 応用編:
    - 第1章 心の理論と発達:
      - 1.1 心の理論の発達段階: applications/1-1-theory-of-mind.md
      - 1.2 誤信念課題の形式分析: applications/1-2-false-belief.md